alias h='history -10'
alias cdd='cd ~/Desktop'
alias fl='fastlane'
alias nv='navi'
alias nvs='navi search'
alias nvq='navi query'
alias pi='pod install'
alias cdp='cd ~/Library/MobileDevice/Provisioning\ Profiles/'
