# 备份同步配置文件 - 从开发目录同步到备份目录
SOURCE_DIR=/Users/qumi/code
DEST_DIR=/Volumes/mli_hd/code
SYNC_MODE=one-way

# 排除一些不需要备份的目录
EXCLUDE_DIRS=node_modules .idea build dist target fonts-master SDK .dart_tool .gradle .kotlin 

# INCLUDE_DIRS=Cleaner

# 默认不启用删除功能, 因为备份的通常是单一的工程
DELETE=false

# 默认为false，建议首次运行时设置为true以预览变更
# DRY_RUN=false

# 显示详细信息
VERBOSE=true
